### ISSUE TITLE
haskell-process-load-file error (wrong-type-argument number-or-marker-p nil) when code has an error

### ISSUE THREAD

**Issue by xinhuazhang** [haskell/haskell-mode#1004]
Hello,

When I use `C-c C-l`, which is `haskell-process-load-file` command, and if there is an error in my code, this error shows. However, if the code is correct, then there is no such error.

    (wrong-type-argument number-or-marker-p nil)

If I use `:l filename.hs` in the *haskell* buffer, it works correctly, no error at all.

I wonder what is going on?

**Comment by gracjan** [comment]
@bergey, is this because of your recent changes?

**Comment by xinhuazhang** [comment]
I have the  other computer which has an old version 20151102.256 and it works fine.

**Comment by bergey** [comment]
@xinhuazhang Can you run `M-x toggle-debug-on-error` and post the backtrace for that `wrong-type-argument`?  Also, on the computer running 21151102.256, is the command that works fine `haskell-process-load-file` or `haskell-process-load-or-reload`?  b0f04d152cfa19886d27f054a5b857ccfe95b68f changed the default binding for `C-c C-l`

I haven't managed to reproduce this yet.  When I have an error in my haskell file, `haskell-process-load-file` shows an error in the minibuffer, like `Setup.hs:2:8: Not in scope: ‘defaultMain’` or `Parse error: naked expression at top level`.

@gracjan Maybe, but it's not obvious to me how.  I didn't change `haskell-process-load-file` at all.  I'm happy to take point on fixing it, since I've looked at these functions recently.

**Comment by xinhuazhang** [comment]
@bergey After I run M-x toggle-debug-on-error and then run either haskell-process-load-file or haskell-process-load-or-reload there is no backtrace showing up. haskell-process-reload has the same problem.

**Comment by xinhuazhang** [comment]
@bergey I think I have figured out the problem.  The path to the file is something like "abc/Ubuntu One/def", there is a space between Ubuntu and One. There is no Ubuntu One any more, I am still doing my work in the directory somehow.

**Comment by bergey** [comment]
Aha!  Thanks for following up.  I was stumped trying to reproduce the issue. Do you mean that you moved the Haskell file, and emacs doesn't know about the rename?  Can we close this, or is there still a problem that we should fix?

**Comment by xinhuazhang** [comment]
If there is no space in the path to  the Haskell file, then it is fine.

**Comment by gracjan** [comment]
Supporting spaces in project paths is one of the things that we should do
someday.

**Comment by Ericson2314** [comment]
^ I hope there is an issue for that?

**Comment by gracjan** [comment]
There is now :)
