### ISSUE TITLE
Devise a performance framework

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#1181]
We would like to add more and more semantic features to haskell-mode and we risk performance degradation. We would not like to be surprised by such basic issues so we need to monitor performance of haskell-mode.

Tasks:

1. Find a performance metric in Emacs that is stable and deterministic.
2. Select a set of functions that are performance sensitive.
3. Attach performance tests that will make sure performance budgets aren't suddenly exceeded.

**Comment by gracjan** [comment]
Notes:

The stable metric seems to be **allocations**.

Performance sensitive functions seem to fall in the following categories:

1. One-off functions run when opening a file.
2. Font lock.
3. Functions bound to a key.

[Emacs Profiler](https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html): this seems to be native profiler that can do both time and allocation profiling.

[EmacsLispProfiler](https://www.emacswiki.org/emacs/EmacsLispProfiler): can measure call count and clock time.

[EmacsLispBenchmark](https://www.emacswiki.org/emacs/EmacsLispBenchmark): measures clock time in execution and clock time in GC. Can measure bytecode compiled functions.

**Comment by gracjan** [comment]
So far so good, some code:

```el
;; This is here to test performance frameworks

(defvar glb nil)

(defun the-bad-function ()
  "sddsds"
  (setq glb (make-list 7 'zonk))
  ;;(setq glb (cons 1 'zonk))
  (sort (number-sequence 1 5120) '<))

(defun extract-the-piece-of-data-we-need ()
  (let ((log (profiler-memory-log)))
    (maphash (lambda (key val)
               ;; `key' is a vector of symbols from the top of the
               ;; stack, it looks like this:
               ;;
               ;; [sort zonk command-line-1 command-line normal-top-level nil nil ...]
               ;;
               ;; We are interested in any stacks that mention the
               ;; function in question because it means either the
               ;; function itself or any of the functions called
               ;; allocated memory. Sum all of it.

               ;;(message "%S: %S" key val)
               (when (catch 'return
                       (mapc (lambda (item)
                               (unless item
                                 ;; cut short at the first nil, there
                                 ;; is nothing interesting past that
                                 ;; point
                                 (throw 'return nil))

                               (when (equal item 'the-bad-function)
                                 ;; found the function
                                 (throw 'return t))) key)
                       nil)
                 (message "Found: %S: %S" key val)))
             log)))


(defun zonk ()
  (profiler-start 'mem)
  (dolist (x '(1 2 3 4 5 6 7 8 9 0))
    (the-bad-function))

  (extract-the-piece-of-data-we-need)
  (profiler-stop)
  (kill-emacs 0))
```

Running it with:

```
$EMACS --batch -Q -l performance.el -f zonk
```

gives:

```
Memory profiler started
Found: [sort the-bad-function while let zonk command-line-1 command-line normal-top-level nil nil nil nil nil nil nil nil]: 695760
Found: [number-sequence sort the-bad-function while let zonk command-line-1 command-line normal-top-level nil nil nil nil nil nil nil]: 1359
Memory profiler stopped
```
```

**Comment by gracjan** [comment]
Note that performance framework will most probably conflict with code coverage tracking, because code coverage needs to do its own allocations. It might be possible to filter out those allocations.

**Comment by gracjan** [comment]
Memory allocation seems to be stable (same number) between batch runs of the same version of Emacs, but it is not stable between versions.

CPU time is not stable at all.

**Comment by gracjan** [comment]
Nice performance trick: https://github.com/gareth-rees/p4.el/issues/112

```el
(inhibit-modification-hooks t)
```

**Comment by gracjan** [comment]
I have not found a performance metric that would be meaningful and stable. Closing as impossible.

**Comment by codygman** [comment]
I had some similar issues in trying to create performance regression tests for my emacs config. I wasn't quite sure what the problem was, but I think I was getting confusing and unexpected results because I was using just the CPU metric which isn't stable.

Here is where I was doing it: https://builds.sr.ht/~codygman/emacs-config

I did something similar to your batch command that resulted in output like:

```
test opening and closing large org file 10 times
took: (53.110200686 115 8.590810290999997)
```

The hope being that with a large org file I could get the baseline of opening with vanilla emacs and it's included org mode, add something like `org-babel-load-languages` to load shell, of which there are at least 50-100 shell blocks in the large org file I open.

I know from the user perspective that this should slow down org mode from doing it manually, but it's seemingly the same. Actually looking back at the data:

```
before loading babel sh:

test opening and closing large org file 10 times
took: (51.280356752 129 6.576739079)

after loading babel sh:

test opening and closing large org file 10 times
took: (50.563274616 129 6.909560387000001)
```

I can see that allocations seem to reflect what's true in practice even though clock time does not. It seems I should have success with tracking performance regressions by paying attention to allocations within same emacs versions according to your findings.

I wonder if a better way might be using something akin to selenium in this case for emacs with xvfb for the use case of `How long until I can interact with emacs after opening a large org file`. I thought running the elisp with emacs in batch mode would be the same, but maybe it's because it's clock time?
