### ISSUE TITLE
REPL often hangs inside :{ and :}

### ISSUE THREAD

**Issue by crocket** [haskell/haskell-mode#1221]
GHCi 7.10.3
haskell-mode 13.18
emacs 24.5.1 built on 2015-09-10
GTK+ 3.16.6

When I type things in :{ and :}, REPL often hangs. I have to press Ctrl+G several times to thaw REPL.

**Comment by gracjan** [comment]
Thanks for the report. We have decided to not support multiline ghci because it is hard.

But seems people are hitting the issue very often so we need a volunteer that will invent a way how to support ghci multiline mode in Emacs.

**Comment by geraldus** [comment]
@gracjan let me repeat myself with few additions :D
0. the issue occurs because after GHCi entered multi-line mode it can't respond to command, most usually because of auto-completions.
1. this can be avoided if we'll use separate hidden process to get completions, types and etc.
2. or we can pop-up separate buffer when user entered `:{` where he write whole code and then sends it to REPL (this is much more user friendly than line-by-line editing, because it is easier to edit wrong code, and it is possible to bind some useful key for sending, canceling and testing input)
2. this is not the case for Inferior haskell because it lack of auto-completion support

**Comment by geraldus** [comment]
Let's close this as #871
