### ISSUE TITLE
Emacs keeps asking for a TAGS file when TAGS aren't used

### ISSUE THREAD

**Issue by jfdm** [haskell/haskell-mode#1234]
I recently updated my Haskell mode and every time I complete a word, emacs is asking for me to point to a tags file. 

The problem is that I do not use tags with emacs, and this new functionality (which might be related to a recent PR #1228) is getting annoying. Is there any chance for this new functionality to be revisited.

**Comment by jfdm** [comment]
Actually, this might not be haskell-mode's fault. Disabling company mode did the trick.

Sorry about that will close the issue.

**Comment by geraldus** [comment]
@jfdm since recent time company annoys me asking about TAGS too, this is not an issue with Haskell sources, but occurs for me in `magit` buffers.  I was suggested to try `tags-revert-without-query`.

But I believe #1128 indirectly affects you.  @gracjan maybe we should provide tags completions only iff `haskell-tags-on-save` is enabled?

**Comment by jfdm** [comment]
Thanks for the quick response, and the tip, will check it out asap. 

Further, I was just using plain-old haskell-mode.

Thanks.

**Comment by gracjan** [comment]
Reopened as this looks important to me. We should make sure that we do not invade usual workflows unless asked explicitly.

Is there a way to use `TAGS` in completions when present but to not auto-generate them?

**Comment by geraldus** [comment]
The short answer is yes.  But the question is not about generating tags, but selecting tags file.  Using existing file without generation looks wrong, because such tags file can be outdated.

@gracjan I think we should redesign `haskell-tags-on-save` a bit.  In my point of view, this variable should have another name and meaning.  Obviously, the only purpose of tags generation is further usage of this information.  Tags can be used for definition jumping and completions (what else?).  So, in my opinion tags-on-save should be called `haskell-mode-use-tags`, and in case if this option is enabled it should automatically generate tags on save and use this info in all related functions / commands.  For example, completion at point function should use tags table only if use-tags is enabled; jump to definition should warn about this option if it is disabled.

Also, at this point I see that some functionality have interactive and static implementations.  I think we should merge such functions in single implementation which conditionally uses session or tags.

**Comment by gracjan** [comment]
Looks like you are right.

Just to confirm: is there a situation when a user might like to use TAGS-based completion but opt to generate tags only explicitly?

**Comment by geraldus** [comment]
> Just to confirm: is there a situation when a user might like to use TAGS-based completion but opt to generate tags only explicitly?

I can't be certain here.  Obvious answer is yes, but more code you write more new completions emerges, so if you want to have accurate completions you have to regenerate tags quite often.  Personally I use interactive mode almost all the time and needs of accurate completions forced me to get habit to reload files on each save very fast.  (Though now I see that I don't use auto-completion often because I type much faster than selecting completion candidate, I dream about fuzzy completions :alien: But completions help to avoid typos!)

**Comment by paldepind** [comment]
I'm experiencing something that might be related. I use company globally. When in a Haskell file I'll be prompted to select a tags file whenever Company is about to show it's completion menu. I have not experienced this before. There seems to be no problems with Company in other major modes.

Also, even though I have `haskell-tags-on-save` set to `t` I cannot see a tags file anywhere?

```
(use-package haskell-mode
  :mode "\\.hs\\'"
  :config
  (require 'haskell-doc)
  (add-hook 'haskell-mode-hook 'haskell-doc-mode)
  (require 'haskell-interactive-mode)
  (require 'haskell-process)
  (add-hook 'haskell-mode-hook 'interactive-haskell-mode)

  (setq haskell-process-auto-import-loaded-modules t)
  (setq haskell-process-log t)
  (setq haskell-process-suggest-remove-import-lines t)
  (setq haskell-tags-on-save t))
``

**Comment by geraldus** [comment]
I'll try to fix this issue in next few days.  There are few options:
+ do not provide completions based on tags when `haskell-tags-on-save` is `nil`
+ do not provide completions based on tags when no TAGS file found
+ conjunction of previous options

I need to think about this stuff a bit.  @gracjan any suggestions?

**Comment by gracjan** [comment]
Well, do not ask for TAGS file in any automatic actions.

**Comment by mmaz** [comment]
I also have company enabled globally, and after upgrading from `haskell-mode 20160321.1029` to `20160410.1309` I am now being prompted to `Visit tags table (default TAGS)` after completing a word in a Haskell buffer, so I have disabled `company-mode` as a workaround. I'm not sure if my use of `evil-mode` is also part of the issue (a [quick skim of this issue](https://github.com/company-mode/company-mode/issues/333) suggests it might be) but I haven't investigated in depth.

**Comment by jfdm** [comment]
@mmaz I do not use evil-mode, and I think @geraldus and @gracjan are on the case.

**Comment by cocreature** [comment]
This _is_ haskell-mode’s fault and the bug was introduced in 0d730998017df9db3cc095a38d21f566bf13646f by @geraldus. Calling that function asks for the tag table, there is a variable by the same name which could probably be used instead to only use the tags table if it is set.

**Comment by geraldus** [comment]
Can someone suggest "right" way to handle this?  My solution is check `haskell-tags-on-save` value.

**Comment by gracjan** [comment]
@geraldus: do:

```elisp
-                (append (tags-completion-table)
+                (append tags-completion-table
                         haskell-completions--keywords)))))
```

**Comment by geraldus** [comment]
Ohhh :(  Apologize

**Comment by gracjan** [comment]
Cool. This should be fixed now.

**Comment by jfdm** [comment]
ah sweet. I will check as soon as the package is available on melpa.

**Comment by mmaz** [comment]
Thanks @gracjan and @geraldus, after the upgrade things are back to normal in my workflow.
