### ISSUE TITLE
Completion and "."

### ISSUE THREAD

**Issue by akermu** [haskell/haskell-mode#1349]
In interactive-haskell-mode, when i try to complete something after a dot, it won't work. For example if i try to complete something like `Ssh.`, it won't show any completions. If i try to complete `Ssh`, it will show the expected candidates, e.g. `Ssh.noPasswords`. If it try to complete `Ssh.n`, it will also complete.

**Comment by geraldus** [comment]
Have you loaded any file into REPL?  To get precise completions in interactive mode you have to either load project's file into REPL (<kbd>C-c</kbd> <kbd>C-l</kbd> by default) or simply start REPL process for current project.

**Comment by akermu** [comment]
To clarify:

```haskell
import qualified Data.List as L
test = L|
```
(Cursor is at | and file is loaded in haskell process without errors)

If i try to complete now, i'll get `L.!!`, `L.++` and so forth. This works as expected. So now when i insert a dot:
```haskell
import qualified Data.List as L
test = L.|
```
(Cursor is at | and file is loaded in haskell process without errors)

and try to complete, I don't get any completions. I have to at least insert one additional character to bet completion suggestions.

**Comment by geraldus** [comment]
Ah, now I see the issue.  Hmm… I guess GHCi will give proper completions too, but can you try to load your file into GHCi and invoke `:complete repl "L."` to be sure?

**Comment by akermu** [comment]
If I invoke the completion command in GHCi manually, I'll get the suggestions.

**Comment by akermu** [comment]
If I find the time, I'll debug the problem this afternoon to find the culprit.

**Comment by geraldus** [comment]
Looks like I know what's going on.
example input, (`|` represents point):
```hs
import qualified Data.Text.Encoding as TE
TE.|
```
+ `haskell-ident-at-point` returns `"TE."` as expected.
+ `haskell-completions-grab-prefix` returns `"TE."` too.

But GHC prior to version 8 have bug in `complete` command, if you try to complete operator (e.g. `:complete repl ">>") it will return you all imported names instead which brings significant slowdowns in Emacs (this bug was resolved (partially) in GHC 8).  To avoid operator completions there is simple check: if last character of input is operator symbol, then completion function does nothing.  Unfortunately this is the case for unfinished qualified name such as `L.`, `TE.` and etc.  So, to resolve this we should make operator check a bit smarter.

**Comment by geraldus** [comment]
@gracjan we still do not know how many people use interactive mode and interactive completions.  What do you think about temporal customization enabling/disabling operator completions?  We can make it true by default (e.g. complete operators) and those who developing with older GHC versions in interactive mode will have an option to avoid slowdowns.

**Comment by gracjan** [comment]
I'd go for auto detect:

1. Set a session var saying that `ghc-is-broken` to nil.
2. If `gcc-is-broken` is nil then do operator completions, otherwise do not.
3. When an operator completion is done check if if it returned only symbols that we expected or did it return some garbage. If garbage then set `gcc-is-broken` to t.

This will make operator lookup slow only the first time it is used and will automatically disable itself when a broken ghc is detected.
