### ISSUE TITLE
Investigate why build system did not reject problems fixed in #1354

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#1355]
See #1354 for details.

**Comment by fice-t** [comment]
It rejected my last PR when I accidentally used `string-join` instead of `(mapconcat #identity` (since it's not available before 24.4). 

Perhaps it didn't fail in https://travis-ci.org/haskell/haskell-mode/jobs/134223966 because of the order of compilation. `haskell-mode` is byte compiled when the specific function was already loaded into the Emacs session.

To be more rigorous it might be better to compile each file in a fresh Emacs session.

**Comment by gracjan** [comment]
So does byte compilation also load a module at the same time? That is surprising!

**Comment by gracjan** [comment]
Now correct, but much slower. This whole build system could be rewritten in Emacs Lisp instead of this annoying Makefile.
