### ISSUE TITLE
Haskell-mode not properly detecting filesystem changes

### ISSUE THREAD

**Issue by LukeHoersten** [haskell/haskell-mode#1372]
In `haskell-mode` buffers only, when:
1. saving a buffer to the filesystem
2. then change the file on the filesystem
3. I would expect emacs to recognize the change and prompt:
  `<filename> changed on disk; really edit the buffer? (y, n, r or C-h)`

This prompt does not occur and instead emacs changes the file on the file system to the contents of my current buffer without a prompt or any indication of a difference at all.

I am using the latest `haskell-mode` from github (installed via melpa nightly) and intero.

**Comment by geraldus** [comment]
I just tried to `echo 123 >> app/Main.hs` and this changes was immediately shown in Emacs.  So I do not see the behaviour you're talking about.  I can't be certain, I use Emacs 25 and likely I see changes because of auto-revert mode.

**Comment by LukeHoersten** [comment]
That will not reproduce the error because emacs will replace the buffer. I'm using `hg update` to replace the file on the filesystem. Not sure exactly how that's different but the result is.

**Comment by mrBliss** [comment]
This is probably the issue described in commercialhaskell/intero#148.

**Comment by gracjan** [comment]
I see the following events:

1. Visit file `X.hs`.
2. Change something in the buffer.
3. Change `X.hs` outside of Emacs, now there are two incompatible changes.
4. <kbd>C-x C-s</kbd>.
5. `X.hs has changed since visited or saved.  Save anyway? (y or n)``, answer <kbd>y</kbd>.
6. `X.hs changed on disk; really edit the buffer? (y, n, r or C-h)`, answer <kbd>y</kbd>.
7. `Wrote X.hs`.

As I see `stylish-haskell` does not overwrite file without asking, if anything we should get rid of the second question in pt. 6.

Note that I've also checked scenario change outside of Emacs is `rm` followed by create new file, it has exactly same result.

So I think that this issue is not `stylish-haskell`. I'll close now, reopen if we are missing something.

**Comment by LukeHoersten** [comment]
Agreed. As @mrBliss pointed out this is most likely an intero issue. This issue is appropriate to close. Thanks.
