### ISSUE TITLE
[Discussion] Haskell summer of Code 2017

### ISSUE THREAD

**Issue by vasanthaganeshk** [haskell/haskell-mode#1499]
Hello all,

I would like to contribute to `haskell-mode` as a Haskell summer of code project. I don't know elisp but I know scheme. I'm confident I can pick up elisp in couple of days. I've used haskell for a couple of months. Can you please suggest some project that needs work, so that I can work on them this summer (I'll take a look at [this](https://github.com/haskell/haskell-mode/issues?q=is%3Aopen+is%3Aissue+label%3Awell-defined-task))? Can you please suggest some mini-projects that I can work on before writing the proposal for familiarizing myself with the repository? I would like to know if someone is willing to mentor me.

My nick on FreeNode is `GreySunshine`.

Thank you,
Vasantha Ganesh Kanniappan.

**Comment by gracjan** [comment]
Hi Vasantha,

It looks like you will have actual time and energy to invest in haskell-mode, this is great new!

There were a couple of tasks that we were not able to tackle due to time and resource constraints:

- unify `session` and `process` in `haskell-interactive-mode`. Those used to be separate, right now there is 1:1 correspondence, but code is still separate. An attempt was made here: https://github.com/haskell/haskell-mode/pull/808
- we have a `get-session` method that does much more than get and should be refactored. More about this in: https://github.com/haskell/haskell-mode/issues/1498
- bring feature parity to `haskell-indentation-mode` so that we can confidently remove `haskell-indent-mode`. Overall `haskell-indentation-mode` could use a lot of fixing.

Note that haskell-mode is a part of a larger ecosystem with LSP and Intero and potentially others. Contributing there indirectly contributes here.

**Comment by vasanthaganeshk** [comment]
I'm trying to understand the architecture of `haskell-mode`, currently I assume that there is one session mapped to one ghci process. If we unify, can you give me a picture of what the new architecture would look like? I don't understand what "session and process are the same" mean as said [here](https://github.com/haskell/haskell-mode/issues/799)(could it mean there are no separate processes for `session` and `process`)?
