### ISSUE TITLE
Is haskell-mode still alive?

### ISSUE THREAD

**Issue by vlatkoB** [haskell/haskell-mode#1586]
I see the last code change was 6 months ago. What is happening?

**Comment by ivan-m** [comment]
@gracjan was the primary maintainer, but they seem to have disappeared.

@purcell seems to have commit privileges and merges in the occasional PR.

**Comment by purcell** [comment]
Wow, that's been a while, then. I haven't been watching this repo much, sorry, but I care about it because I'm working primarily in Haskell these days. It's fair to say that there's quite a lot of baggage here, between the complex syntax highlighting, indenting and interactive modes, so a spring-cleaning would be beneficial at some point IMO. At the same time, the code works pretty well for me in conjunction with Intero. I'll have a quick look through the issues and PRs and see if there are any quick wins/fixes.

**Comment by vlatkoB** [comment]
@purcell, thanks for quick reaction. :-)

**Comment by vlatkoB** [comment]
Maybe another spring cleaning... :-)

**Comment by vlatkoB** [comment]
@purcell Thanks for your work. :-)

**Comment by purcell** [comment]
Still a bunch more to do, tbh... will try to find some time soon.
