### ISSUE TITLE
Add support for tab-completion to haskell-interactive-mode

### ISSUE THREAD

**Issue by hvr** [haskell/haskell-mode#178]
This is basically the same to #164 but for `haskell-interactive-mode`

**Comment by geraldus** [comment]
@hbv there is come caveat: `haskell-process-get-repl-completions` uses sync request behind scenes hanging Emacs until REPL request will be received. This is very annoying side effect with big projects with template haskell, because reloading sources takes notable time. Can you say is it possible to some how provide completions for `auto-complete` asynchronously? I'm trying to find time to find asynchronous completions for `company-mode` and it will be great if we could implement some unique asynchronous mechanism in `haskell-interacive.el` which could be easily adopted by both `company-mode` and `auto-complete`.

**Comment by gracjan** [comment]
Looks like this is working.
