### ISSUE TITLE
Remove yasnippet hidden files from haskell-mode/snippets/haskell-mode

### ISSUE THREAD

**Issue by jfeltz** [haskell/haskell-mode#305]
I'm going to suggest either documenting their function, or removing the yasnippet hidden files. (e.g. .yas-ignore-filenames-as-triggers). Those can cause a train wreck of time-waste and frustration for users new to yasnippets. I eventually by accident figured out that my snippet additions weren't working due to spotting that hidden file. Thanks for the consideration.

**Comment by gracjan** [comment]
yas-snippets causing issues, solution is to use them outside of haskell-mode: https://github.com/haskell/haskell-mode/pull/435

**Comment by capitaomorte** [comment]
@gracjan, I don't understand what you mean. Are you sure your comment relates to this issue #305?? I read your linked discussion but didn't understand where yasnippet may be at fault.

If it doesn't, open a new issue and be sure to be clear about it. Otherwise time might be wasted.

**Comment by gracjan** [comment]
For more info please read: https://github.com/haskell/haskell-mode/issues/361

**Comment by capitaomorte** [comment]
@gracjan, you typed:

> yas-snippets causing issues

Do you by `yas-snippets` mean the project "Yasnippet"? 

* If **yes**, I ask you to explain what issue the yasnippet project is causing, as I can't discover from the linked discussions, and how it relates to #305.
* Otherwise, this discussion has no place here. If you need support or want to report a bug, open a separate issue.

**Comment by gracjan** [comment]
By 'yas-snippets causing issues' I mean 'yas-snippets causing issues in context of haskell-mode'. Or to put it even more clear: 'haskell-mode is causing issues due to how yas-haskell-snippets are packaged and used'. jfeltz described issues caused by yas-haskell-snippets perfectly so I'll not repeat it here.

I'll repeat again: this issue is caused by haskell-mode yas embedding. The solution is to use separate yas-haskell package as reported here: https://github.com/haskell/haskell-mode/issues/361.

Discussion about yas-haskell-snippets should be taken over to the original shnippet repo that is here: https://github.com/LukeHoersten/shnippet.

**Comment by capitaomorte** [comment]
I don't understand

* what "haskell-mode yas embedding" is.
* what `haskell-yas` is.

Do you mean any snippets stored in the `snippets/haskell-mode` subdirectory when you clone Yasnippet with submodules. If you mean this, and if those snippts do exist (I didn't check), then they are maintained by the [yasnippet-snippets](https://github.com/AndreaCrotti/yasnippet-snippets) project, and not Yasnippet.

The issue that @jfeltz described had to do with snippets without explicit trigger keys, a behaviour that still works but is deprecated and undocumented. I don't know how it relates to your issue, but I haven't understood your issue either.

Anyway, it's good to hear that this discussion I don't understand is being taken somewhere else. Good luck!

**Comment by gracjan** [comment]
Thanks for the hint about https://github.com/AndreaCrotti/yasnippet-snippets!

**Comment by LukeHoersten** [comment]
`.yas-ignore-filenames-as-triggers` is included because this is recommended by the YAS author and YAS will evidently stop supporting name triggers as a deprecated feature anyway.
