### ISSUE TITLE
haskell-mode-jump-to-def-or-tag sometimes doesn't jump

### ISSUE THREAD

**Issue by MichaelXavier** [haskell/haskell-mode#351]
Sometimes when I'm editing haskell code and I hit `M-.`, which is bound to `haskell-mode-jump-to-def-or-tag`, instead of jumping to the location where that tag is defined, it just puts a message in my minibuffer "Defined in `Some.Module`.

Strangely enough, if I manually run `find-tag` with the same tag, it jumps to the file as expected. I wish I had a better repro case, I just notice it happen several times a day at work. Let me know if there's any more information I could provide that would help.

**Comment by gracjan** [comment]
@geraldus: can you try to reproduce this issue in GHCi so that we know when GHCi returns a file name and when it returns module name?

**Comment by geraldus** [comment]
I have no clue how to reproduce module name issue in GHCi itself.  I played with `:info` command (which is used under the hood) but it always prints me file location.  The simplest way to resolve this issue I see is to examine value returned by `haskell-mode-find-def` in `haskell-mode-jump-to-def-or-tag` directly rather than calling `haskell-mode-handle-generic-loc`.  The latter function is culprit of reported behavior: if `haskell-mode-find-def` return a file-value it jumps to location, if module-value it prints it.

**Comment by llelf** [comment]
One case when it reproducibly doesn't jump is: you are jumping from the module in `test:…` to a symbol defined in module in a `library`. Very frustrating. I could make a trivial package demonstrating the issue if it helps.

This case worked fine in v13.12 (I haven't been upgrading for a long time, hence this particular old version).

**Comment by dredozubov** [comment]
FWIW i think falling back to `find-tag` is a good idea, because the issue is quite annoying and it should make a decent workaround for it.
