### ISSUE TITLE
haskell-yas.el should be a separate package

### ISSUE THREAD

**Issue by Fanael** [haskell/haskell-mode#361]
As per https://github.com/haskell/haskell-mode/pull/356#issuecomment-58934768. The bugtracker is usually the best place to track TODOs like this.

**Comment by gracjan** [comment]
@purcell, for the record `haskell-yas` seems to be a rename of `shnippet` that is alive and well in a github report maintained by `shippet` author: https://github.com/LukeHoersten/shnippet. `haskell-yas` does not offer any functionality over what `shnippet` offers.

**Comment by gracjan** [comment]
For posterity reference accidental issues that one of users experienced: #305.

**Comment by LukeHoersten** [comment]
I actively maintain both shnippet and haskell-yas (they are the same just a rename). The reason it was originally moved into haskell-mode was because it allows us to have completions like `lang` that use haskell-mode to expand to all possible lang pragmas. YAS itself comes packaged with some basic haskell completions as well.

I'm not sure if the best course of action is to:
1. kill off my external repo and just manage through haskell-mode
2. try to get these merged into YAS proper and just have the `haskell-mode` dependent snippets say in `haskell-mode` like `lang` expansion.
3. Use subrepos and link back to my `schnippet` repo

What do you guys think?

**Comment by gracjan** [comment]
If snippets are to be fully supported citizen of haskell-mode there needs
to be documentation for that and description how to enable those.

**Comment by purcell** [comment]
I personally strongly feel that `haskell-yas` should disappear, and there should just be a properly-packaged version of `schnippet`, or a derivative thereof, ideally under the `haskell` github org.

There's no fundamental connection between the haskell snippets and `haskell-mode` in terms of code. `yasnippet` has to be installed separately from `haskell-mode` anyway, and many people don't use it at all. Packaging optional extras separately is the right thing to do in these days of pervasive Emacs package management.

**Comment by purcell** [comment]
To clarify, it may of course make sense for `schnippet` to depend on `haskell-mode` in order to provide correct snippets, but no part of `haskell-mode` needs `haskell-yas`/`schnippet`.

**Comment by LukeHoersten** [comment]
I think that's the right approach Steve. Moving it to the Haskell github
would alleviate a lot of the questions I've seen too about what's the
officially supported version. I'll do that soon. Thanks for the feedback.

**Comment by LukeHoersten** [comment]
https://github.com/haskell/haskell-snippets
