### ISSUE TITLE
Interactive-Haskell hangs

### ISSUE THREAD

**Issue by xificurC** [haskell/haskell-mode#416]
Hi there,

I'm working on [scheme48hours](https://en.wikibooks.org/wiki/Write_Yourself_a_Scheme_in_48_Hours) (you can find my code that has the discussed issue [here](https://github.com/xificurC/scheme-interpreter)) and the repl just hangs on me when I start the custom repl in it.

To be more precise and give steps to reproduce:

- open `Main.hs` in Emacs
- load it with `C-c C-l`
- run `runRepl`
- `M-x completion-at-point`

This freezes emacs and I have to kill ghc to get control. Then if I check the `*haskell-process-log*` I see over 1k lines of completion options. The repl works fine in a terminal.

If this isn't a haskell-mode issue I'll be glad to move the question wherever I get pointed. Thank you in advance.

**Comment by chrisdone** [comment]
It's because communication with the GHCi process is exclusive. You can only run one command at a time. Either running something in the REPL or getting completions, but not both. When I add unix domain socket-based communication, that limitation will be lifted, but I have no immediate plans to implement that

**Comment by xificurC** [comment]
I see. Thank you for the explanation Chris, I will just stick to running these things outside of emacs I guess.

Peter
