### ISSUE TITLE
New indentation — using backspace to move to the previous indentation position

### ISSUE THREAD

**Issue by EDmitry** [haskell/haskell-mode#500]
I have noticed one difference between original haskell-indentation and the new one. If I have (the cursor position is indicated with `^`):

```
some :: Int -> Int
        ^
```

Hitting `<Backspace>` would move the cursor to the beginning of the line (the previous valid indentation position), but in the new indentation mode it just deletes one space.

I haven't looked more closely why this happens, but I have verified the difference exists when just switching branches, so all other settings are completely identical in my set up.

**Comment by EDmitry** [comment]
I visited the hi2 repo and found out that this is expected (del is not binded anymore). S-Tab works well. The main reason I was using Backspace is because of this bug: https://github.com/haskell/haskell-mode/issues/276

**Comment by gracjan** [comment]
In `hi2` TAB cycles forward till the last position and the backward. S-TAB cycles backward. DEL is not bound and does it own usual thing.

#276 should affect only `haskell-indent` which is different than `haskell-indentation(hi2)`.

So this is not a bug.

**Comment by EDmitry** [comment]
Is there a possibility to add an option to bind it back? I realized I kind of got used to it and don't mind any possible problems with it (I didn't experience any to be honest). It's hard to do anything with muscle memory once it has been acquired.

**Comment by gracjan** [comment]
Can you bind <backspace> to unindent for you locally, use it a little and see how it feels?

In theory binding <backspace> is a good idea, in practice there were problems with exact mechanics how it should work. <backspace> has already many options associated with it in Emacs.

Can you find out how other modes for indentation-based languages bind edit keys? Python mode usually is a good reference point.

**Comment by EDmitry** [comment]
I have tried Python and it seems like `<Backspace>` moves to the previous indentation place:

arr = [100] * 10000000

for x in range (0, 10000000 - 1):
    arr[x] = arr[x] - 1
    if arr[x] == 0:
        print x
        ^<Backspace>
    ^<Backspace>
^

**Comment by gergoerdi** [comment]
I've just updated my haskell-mode from an ancient version and immediately noticed the lack of this feature. My problem is not that unindent-or-delete-backwards is not bound to backspace by default; the problem is that I don't see where the functionality is implemented! (in v13.14.2)

Does that mean I need to revert to my old version from 2012 to get this functionality back?

**Comment by gergoerdi** [comment]
Would something like this work?

```elisp
(defun haskell-indentation-at-beginning-of-line ()
  (= (haskell-indentation-current-indentation) (current-column)))

(defun haskell-indentation-unindent-or-delete-backwards ()
  (interactive)
  (if (haskell-indentation-at-beginning-of-line)
      (haskell-indentation-indent-backwards)
    (backward-delete-char 1)))
```

**Comment by gracjan** [comment]
Authors of haskell-indentation provided two ways to control indentation:
- TAB cycle that goes over all possible indentations for a line
- SHIFT-TAB to unindent

**Comment by gergoerdi** [comment]
Yes, and neither of them is what I and the OP want. With the `haskell-indentation-unindent-or-delete-backwards` function mapped to `[backspace]`, you can use backspace to delete one indentation level if you press it at the start of a line, or one character otherwise. This is exactly the functionality that OP was missing in the newer versions.

I'll prepare a proper pull request that adds these functions and maps `[backspace]` in `turn-on-haskell-indentation`, so that it matches its own documentation which states

> `turn-on-haskell-indentation`
>
>  Improved variation of `turn-on-haskell-indent` indentation mode.
>  Rebinds `<RET>` and `<DEL>`, so that indentations can be set and
>  deleted as if they were real tabs.

**Comment by gracjan** [comment]
I wasn't the one deciding to remove this functionality.

Please remember to add test cases in `tests` directory for the new
functionality you are providing.

Note that TAB-cycle functionality is also buggy at this point. Since you
are going to fix that part of the code you could look also in this issue.

Please also extend documentation so that it mentions all the
TAB/S-TAB/backspace options to handle indentation.

Thanks!

**Comment by gergoerdi** [comment]
@EDmitry can you try my pull request and see if it works for you?
