### ISSUE TITLE
Operators not getting face applied

### ISSUE THREAD

**Issue by ankhers** [haskell/haskell-mode#503]
I've noticed recently that operators (`$`, `*`, `+`, etc) are no longer getting a face applied to them.

![screen shot 2015-03-12 at 11 38 35](https://cloud.githubusercontent.com/assets/750786/6621394/bd62cece-c8ac-11e4-8118-0edcb652f6f2.png)

In that screen shot, I expect `*` and `+` to have the same colour as the `=` and `::`

**Comment by chrisdone** [comment]
Reproducing here too. May be caused by https://github.com/haskell/haskell-mode/commit/b53ba49c61b2881ec93e07c852725e5b2e592d81. Probably the syntax table makes sense but it's a regression in terms of highlighting.

**Comment by gracjan** [comment]
@ankhers: Good catch! Thanks!

The story of this is rather interesting one so let me share:

Haskell operator characters used to be in Emacs symbol class, that was a mistake because 'emacs-symbol' is 'haskell-variable' or 'haskell-contructor' that is 'identifier'. Then there was a regexp setup to highlight \\_ as `haskell-operator-face`. Now documentation states that `haskell-operator-face` is `font-lock-function-name-face` when code says it is `font-lock-variable-name-face`, neither one seems proper.

Note also that `haskell-mode` post-fixes underscore and apostrophe into \w (word constituting class) characters.

Note also that neither `c++-mode` nor `python-mode` define special syntax rules for operators but then those languages are more keyword driven compared to Haskell.

**Comment by gracjan** [comment]
Meanwhile Agda has this: http://code.haskell.org/Agda/src/data/emacs-mode/agda2-highlight.el
