### ISSUE TITLE
haskell-mode needs cl-lib on Emacs23

### ISSUE THREAD

**Issue by PinkMushroom** [haskell/haskell-mode#604]
Debian wheezy emacs 23 does not seem to have cl-lib

So a fresh install of haskell-mode fails

Cannot open load file "cl-lib"

AFAICT this seems to be a problem in emacs23 only.

**Comment by gracjan** [comment]
True, `haskell-mode` requires `cl-lib` to be present. The easy way is to install `cl-lib` on Emacs 23.

As far as I know Emacs 23 lacks also a default package manager and that means we do not know what kind of way to get `cl-lib` to advice.

**Comment by gracjan** [comment]
@PinkMushroom: what do you suggest we do?

**Comment by gracjan** [comment]
We have this: https://github.com/haskell/haskell-mode/blob/master/haskell-mode-pkg.el.

How did you install `haskell-mode` on Emacs 23?

**Comment by PinkMushroom** [comment]
i installed using git clone/make

as for suggestions: i'm not too familiar with installation of emacs package, but maybe
 - include the appropriate cl-lib as part of the distribution 
 - add "you need cl-lib for emacs23" to the readme

i believe there's an issue that if cl-lib is included as part of the distribution by default there might be conflicts with emacs24. someone more knowledgeable than I will have to let me know if that's a problem.

obviously, at this point, i'm volunteering to test the solution :-)

**Comment by gracjan** [comment]
We distribute cl-lib along haskell-mode for tests under Emacs 23. It is in
tests/compat/cl-lib.el. You may take it from there.

If you know what kind of instructions would make it clear to Emacs23 users
please create a pull request with changes to README.md. I could invent
something but that would be guessing so you are a better person to write it.

Have you considered upgrading Emacs? It's free, you know...

**Comment by PinkMushroom** [comment]
i would love to upgrade emacs but would not love upgrading debian to unstable to do it...
ok-i'll work on some verbage

**Comment by geraldus** [comment]
@PinkMushroom you don't need to upgrade Debian to unstable branch, because you can use [backports](http://backports.debian.org) to install Emacs24 easily. Here is quick instructions:

For wheezy add this line:
```
deb http://http.debian.net/debian wheezy-backports main
```
to your `sources.list` (or add a new file with the ".list" extension to /etc/apt/sources.list.d/) You can also find a list of other mirrors at https://www.debian.org/mirror/list
Run `apt-get update`.

Now you can install Emacs24 package (GTK+) [1] or Emacs24-Lucid [2] or even Emacs24-nox without GUI support [3] 
[1] https://packages.debian.org/wheezy-backports/emacs24
[2] https://packages.debian.org/wheezy-backports/emacs24-lucid
[3] https://packages.debian.org/wheezy-backports/emacs24-nox
using following command:
`aptitude -t wheexy-backports install Emacs24`
or
`ap-get install -t wheezy-backports install Emacs24`.

**Comment by PinkMushroom** [comment]
oops. i shouldn't have closed.  So here is my suggestion

@geraldus yes- i could use backports - but still - are there users that for whatever reason will be stuck with emacs23 ? then they will want to know how to get things working.

regardless I'm trying to figure how to create a pull request with the note added to the README.md.

**Comment by geraldus** [comment]
@PinkMushroom btw, Jessie has been released yesterday.

**Comment by PinkMushroom** [comment]
ok. i created the pull request....

**Comment by gracjan** [comment]
Closed via #632.

**Comment by gracjan** [comment]
@PinkMushroom: Thanks!
