### ISSUE TITLE
PowerShell hangs on haskell-process-generate-tags

### ISSUE THREAD

**Issue by ibraimgm** [haskell/haskell-mode#609]
Hello! I recently updated `haskell-mode` and noticed that the tag generation (when I save/reload a file) gets "locked" into powershell. I don't know why, bu when the current command is run inside emacs:

```elisp
 (format ":!powershell -Command \"& { cd %s ; hasktags -e -x (ls -fi *.hs -exclude \\\"#*#\\\" -name -r) ; exit }\""
                            (haskell-session-cabal-dir
                              (haskell-process-session (car state))))
```
Everything just freezes. The equivalent command, in the shell itself, does not hang.
Why we must do this with powershell? Is there a specific reason to not use `hasktags` directly?
On my configuration, I changed the above line with:

```elisp
(format ":!hasktags --output=%s\\TAGS -x -e %s"
                            (haskell-session-cabal-dir (haskell-process-session (car state)))
                            (haskell-session-cabal-dir (haskell-process-session (car state))))
```
And the result looks the same to me (it's even recursive).
If the above solution is acceptable, I can send a patch/pull request later.

Related:
https://github.com/haskell/haskell-mode/issues/49
https://github.com/haskell/haskell-mode/issues/447

**Comment by gracjan** [comment]
Well, I like it. But then I'm not using Windows...

I guess the powershell trick is from times before when hasktags was
recursive in itself.

One thing: can you check if paths with spaces in them work for the %s
substitution? Windows likes spaces and we need to support that. Just put
your project inside C:\Documents and Settings and that should give you a
clue if this works or not.

**Comment by ibraimgm** [comment]
Good catch. I will try this tomorrow and make a pull request if it works.

**Comment by TimoFreiberg** [comment]
I had the same problem, the powershell command caused an error. It also caused the exact same error if I typed the command in the powershell myself, though. Maybe it depends on the system environment?
Anyway, I replaced the command with the second snippet (which just uses hasktags) in my haskell-commands.el and the REPL no longer hangs.

Paths with spaces don't work ("warning: no files found!"), but I could fix this by escaping the paths with quotes.
Current working version:
```
                 (format ":!hasktags --output=\"%s\\TAGS\" -x -e \"%s\""
                            (haskell-session-cabal-dir (haskell-process-session (car state)))
                            (haskell-session-cabal-dir (haskell-process-session (car state)))))
```
The escaping is kind of a hack of course, but I'm way too much of a newbie in Emacs and LISP to try a more elegant solution.

I only just noticed because I don't have to restart the process all the time anymore: Is it correct that files aren't automatically loaded into the REPL when saved? Or am I doing something wrong?

**Comment by gracjan** [comment]
Double quotes are good enough for windows provided the last char in path is
not backslash.

I do not know how to answers your question.

**Comment by ibraimgm** [comment]
@TimoFreiberg , looks like you're faster than me :+1: 

Anyway, about your question:
> Is it correct that files aren't automatically loaded into the REPL when saved? Or am I doing something wrong?
You have to cal `haskell-process-load-file` to reload the file on teh REPL (I bound it to `C-c C-l`). If you want to reload when you save, you might need to create a hook in `

**Comment by gracjan** [comment]
Wait, where is the pull request?

**Comment by TimoFreiberg** [comment]
Recreated it, I thought I did something wrong before.

**Comment by gracjan** [comment]
Now it works. Thanks!
