### ISSUE TITLE
Fix haskell-show.el

### ISSUE THREAD

**Issue by gracjan** [haskell/haskell-mode#615]
There is a file called `haskell-show.el`.

1. It is not referenced from any other file.
2. It is not documented in wiki, it is not documented in texi.
3. It depends on external program https://hackage.haskell.org/package/sexp-show that nobody has installed.
4. It depends on `Read` and `Show` instances being the derived versions.

In its current form it cannot be useful to people outside of very narrow group of enthusiasts that need better `Show` presentation.

What do we do with this?

**Comment by ivan-m** [comment]
Apparently sexp-show was downloaded 21 times in the last 30 days...

That said, I think it was one of @chrisdone's experiments that doesn't seem to have gone anywhere (since he no longer maintains it) so it's probably worth deleting.

**Comment by gracjan** [comment]
Those downloads might be due stackage building everything: https://www.stackage.org/package/sexp-show.

@ivan-m: Can you prepare a pull request cleaning this up?

**Comment by ivan-m** [comment]
Please ignore the first one; I made a typo and did a force-push to fix it.

**Comment by Hi-Angel** [comment]
> Apparently sexp-show was downloaded 21 times in the last 30 days...

"9 downloads in the last 30 days" still. I'm really curious where these are coming from. Well, 1 of them was me just because [I was trying to figure out what it does](https://github.com/purescript-emacs/purescript-mode/pull/44). But I only learned that invoking `sexp-show --help` hangs, as if it waits for something. But no clue who's still downloading this undocumented and a decade as abandoned project.
