### ISSUE TITLE
haskell-interactive-mode-completion-at-point-function can take too long

### ISSUE THREAD

**Issue by ikirill** [haskell/haskell-mode#637]
In one of my projects I import many modules (GL, GLFW, Lens, all not qualified), and `haskell-interactive-mode-completion-at-point-function` returns something like 14k different completions at top level (e.g., if I type `main (` at the prompt). I find it's quite slow, hanging my emacs for a few seconds whenever `company` tries to complete at the top level.

To show what I mean:

    λ> :complete repl 5 "main ("
    5 14802 "main ("
    "!!"
    "!!"
    "#"
    "#%%="
    "#%%~"

Importing the modules qualified helps, but only up to a point because then the completion list just contains many of the same things but with a module name prefix.

Would it make sense to implement, say, a bound on the number of completions? IIUC the completions are generated once, and then refined as the user types more, so returning only the first 1k (say) would mean that some are not going to be displayed at all, but perhaps that's better than pausing emacs?

It seems unlikely that 14k different completions would ever be so useful on their own, because I imagine it's a lot of effort to pick the one thing the user meant to type out of all of them. Personally, I'd prefer no completions to intermittent unresponsiveness. Turning off completion entirely solves this, but it's unsatisfactory.

Note: I haven't checked what exactly is slow here: haskell-mode reading in 14k completions or their processing by company.

 `haskell-process-get-repl-completions` returns a similar number of completions, I think, causing pauses when I edit a haskell file.

**Comment by gracjan** [comment]
@geraldus is working on more async competions, might be it will solve or at least alleviate your issues.

**Comment by geraldus** [comment]
@ikirill currently completions are collected synchronously, that's why company hangs emacs on each keystroke, I've already opened issue related to this (https://github.com/haskell/haskell-mode/issues/606). I've written very simple asynchronous company backend (https://github.com/geraldus/company-interactive-haskell-backend), but work still in progress. I need to make some minor tweaks and implement some features. I hope I will be able to manage this in nearest future.

**Comment by ikirill** [comment]
@geraldus Okay. BTW, isn't `haskell-doc-current-info--interaction` already async?

Also, I think async completion doesn't really solve the problem of having 14k strings to read in and process on every other keystroke: that's too much work to be done too often if emacs is to feel responsive.

**Comment by ikirill** [comment]
Also, I noticed you use company-grab-symbol: haskell-mode changed this at some point and now "." has syntax class punctuation, so "Control.Monad.whatever" would not be recognized as a single symbol, only "whatever", which isn't right.

**Comment by ikirill** [comment]
I solved this problem for myself by writing an async company backend that limits max number of completions: https://github.com/ikirill/haskell-mode/blob/pr-company-async/haskell-company-async.el

Would you be interested in this as a PR? It should be functional, but I'm not sure if it fits the structure of haskell-mode.

**Comment by geraldus** [comment]
@ikirill, surely, I suppose limiting list of candidates is good idea, also `:complete` command accepts optional limit parameter already.

I've used `company-grab-symbol` in sake of speed, I have plans to use same algorithm as in `haskell-process-completions-at-point`, because it will give also completions of language pragmas and etc. I need to discuss some aspects of issue.

We discussed the problem of `company` dependency and decided not to bring it, that's why I've written separate package.

I'll have a deeper look at your code later this day, have no much time right now. Will ping you here.

Also I have plans to make my backend more feature full, e.g. support annotations and etc. I'll create a README today.

**Comment by geraldus** [comment]
@ikirill hey, your elisp is much more robust than mine! I would be glad for PR. However I want to make some changes and improvements.

First, I would prefer for annotation module name from where completions comes rather than types. Type information could go to echo area. This how things organised in `company-ghc` backend (for `ghc-mod` users).

Second, company documentation recommends use text properties for candidates list for annotations. So we can asynchronously ask a list of completions, then asynchronously fetch `:info` for each completion. This will give us type signature and module name at once. Then we could add this info as special text (symbol?) properties for each candidate in list. Now `meta` and `annotation` commands need just to extract that properties from candidates.

Third, I wan also provide completions for pragma names, extension names, ghc-options. Looks like this things could be done synchronously, because there is some vars already (https://github.com/haskell/haskell-mode/blob/master/haskell.el#L78-L95): `haskell-ghc-supported-options`, `haskell-ghc-supported-extensions`. But for pragma names I suppose we need to interact with REPL. All REPL interaction should be async, because if REPL is in reloading state, sync request hangs Emacs.

Finally, I want to provide completions from standard function (I believe it is `dabbrev-expand`) also, for local definitions, such as in `let` and `where` bindings if none candidates was found earlier.

However, I would be glad to accept PR as is and make this stuff myself (though I need to learn some things from your code such as when-let, I'm still learning Elisp).

**Comment by ikirill** [comment]
> So we can asynchronously ask a list of completions, then asynchronously fetch :info for each completion. 

This would be far too slow, taking a noticeable amount of time for each candidate.

>  I wan also provide completions for pragma names, extension names, ghc-options.

I think it's just a matter of copying the prefix-recognizing code from `haskell-process-completions-at-point` to `haskell-company-async`.

> But for pragma names I suppose we need to interact with REPL.

No, the whole point of those variables is that they are initialized once, from shell (https://github.com/haskell/haskell-mode/blob/0a70f4400c08b622bdf4569d3bbd8152d010ae5b/haskell-customize.el#L332, see the pr it came from) and don't change, since the ghc version doesn't change. So no need for repl.

> Finally, I want to provide completions from standard function (I believe it is dabbrev-expand) also, for local definitions, such as in let and where bindings if none candidates was found earlier.

I'm not sure what you mean.

Feel free to just copy the code directly if you want.

**Comment by geraldus** [comment]
As for last statement: consider local var declaration `let myVar = someStuff`, now If you ask REPL for `myV` completions it will return nothing, however hitting `M-/` (which calls `dabbrev-expand` in my case) will be able to complete it with missing `ar`. So if we can't find completion for prefix using variables or REPL, we could iterate over `dabbrev-expand` completions.

**Comment by geraldus** [comment]
> But for pragma names I suppose we need to interact with REPL.

I meant completions for `LANGUAGE`, `GHC-OPTION`, `DEPRECATED`, etc.

**Comment by geraldus** [comment]
@ikirill there were some updates on default completion function recently, because your issue is related to amount of completions I guess that changes will not solve this, but it will be good if you can test these updates.  So, can you temporarily fallback to `company-capf` backend and make some tests?

**Comment by geraldus** [comment]
@ikirill, by the way, I've found a bug, which is likely related to your issue (if I understood correctly you have a lot of operators): REPL returns all imported names, when asked to complete operator, e.g. `complete repl ">>"`,  described here #739.

**Comment by gracjan** [comment]
So this bug is in GHC, fixed in GHC 8.0. For now the situation in haskell-mode that triggers this GHC bug is disabled and will be fixed and enabled again when #1253 is done.
