### ISSUE TITLE
Highlighting issues with strings containing double-quotes with backslashes

### ISSUE THREAD

**Issue by sumitsahrawat** [haskell/haskell-mode#683]
![emacs skyrim_007](https://cloud.githubusercontent.com/assets/5645741/7899693/bc52132c-074b-11e5-8e65-f5cfe6f34042.png)

**Comment by gracjan** [comment]
Hi @sumitsahrawat , nice catch!

This issue is caused by these lines: https://github.com/haskell/haskell-mode/blob/master/haskell-font-lock.el#L336-L343

I tries to match any three or more consecutive punctuation chars (there are three backslashes in your example) and remove any comment starting from them if they are not only dashes. Or more simply `--` is a comment starter whereas `\--` or `--\` are possible operators in Haskell.

Can you try and fix this yourself? Would be very appreciated!

**Comment by sumitsahrawat** [comment]
I would love to do so, but I'm not very conversant with elisp.

**Comment by gracjan** [comment]
Well, that part is just a big overgrown regexp, nothing to be scared off! Give it a try!

**Comment by sumitsahrawat** [comment]
I'll try and return to it.
