### ISSUE TITLE
Haskell-mode was invaded by Eclipse users

### ISSUE THREAD

**Issue by wwat** [haskell/haskell-mode#762]
If I do C-c C-l I just want it to load ghci by default. I do not want that stupid, stupid system to ask me whether I want to create a "project". Do you have no taste?

**Comment by ivan-m** [comment]
No, we obviously don't.

And you obviously don't have any manners which is why you need to state this three times (and creating two new issues on the topic).

**Comment by gracjan** [comment]
@wwat: I see that you are disappointed. It is always very sad for us to see disappointed users.

Note that `haskell-mode` grew a lot. We support more than GHCi, there is also `cabal repl`, `stack repl`, we had `cabal-dev ghci`. That is a lot and requires infrastructure to support.

@wwat: Are you able to help us out with improving `haskell-mode` quality?

(@wwat: Note that I find your emotional reports very important because we need emotional `haskell-mode` users. Having said that some people may get sad reading those.)

**Comment by wwat** [comment]
@gracjan I am only involved in open-source when I get paid for it, because of the Joker's expression:"If you are good at something, you never do it for free". 

So, even reporting this, is already going against my principles. 

So, *yes*, I can help you with this (I wrote a couple of major modes already), and I am the right user/developer, but unless you have a bag of cash to spray around, I am not going to. 

I do sincerely believe in that if you are not capable of reducing the number of bugs in your system to zero without adding new features in a year, that you can better just stop. Since Haskell-mode is close to a decade old, and the scope of all it needs to do is fairly limited, I don't really see why it hasn't reached that point yet.

**Comment by gracjan** [comment]
Many people would love to get paid for working on haskell-mode. Can you
help organizing paid development for haskell-mode?

**Comment by wwat** [comment]
@gracjan Do you always ask such stupid questions?
