### ISSUE TITLE
Error on "C-c C-l"

### ISSUE THREAD

**Issue by budsbenzer** [haskell/haskell-mode#784]
Hello,

I seem to have the same issue as reported in [this issue](https://github.com/haskell/haskell-mode/issues/763). However, I am willing to help you debug it. ;)

I am using haskell-mode version 20150727.354 from ELPA, on GNU Emacs 24.5.1.

Whenever I try to launch a new Haskell session via `C-c C-l`, I get the message `haskell-utils-read-directory-name: Wrong type argument: arrayp, nil`. On following invocations of `C-c C-l`, the message is `haskell-session-current-dir: No current directory.`

The backtrace for the first invocation of `C-c C-l`:
```lisp
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  file-truename(nil)
  haskell-utils-read-directory-name("Cabal dir: " nil)
  haskell-cabal-get-dir()
  haskell-session-cabal-dir(((name . "haskell") (process (name . "haskell") (is-restarting) (current-command) (suggested-imported) (sent-stdin) (evaluating) (session (name . "haskell") #1))))
  haskell-process-start(((name . "haskell") (process (name . "haskell") (is-restarting) (current-command) (suggested-imported) (sent-stdin) (evaluating) (session (name . "haskell") #1))))
  haskell-session-make("haskell")
  haskell-session-new-assume-from-cabal()
  haskell-session()
  haskell-process-load-file()
  haskell-process-load-or-reload(nil)
  #<subr call-interactively>(haskell-process-load-or-reload nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> haskell-process-load-or-reload nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (haskell-process-load-or-reload nil nil))
  call-interactively(haskell-process-load-or-reload nil nil)
  command-execute(haskell-process-load-or-reload)
```

If you need more information, please tell me.

**Comment by ocecaco** [comment]
A quick way to fix this problem is to set `haskell-process-load-or-reload-prompt` to `t`. Then it will ask you for a session name and directory. This problem only occurs for me when I'm working on files which are *not* in a Cabal project.

What I've found out from some debugging today: The reason for this error is that when `haskell-process-load-or-reload-prompt` is `nil`, it doesn't ask for a directory, instead it returns the default directory passed as the 2nd argument to `haskell-utils-read-directory-name`. The second argument is `nil` as you can see which causes the error later on.
