### ISSUE TITLE
haskell-indentation should line up function arguments

### ISSUE THREAD

**Issue by ElectricCoffee** [haskell/haskell-mode#813]
Emacs will consistently do this: (`□` = the other indent point(s))

    myFunction = maybe arg1
    □            arg2
    □            arg3

Instead of doing this:

    myFunction = maybe arg1
    □            □     arg2
    □            □     arg3

When putting arguments on a line of their own, this could lead to some edge cases where the code gets evaluated wrong due to the indentation level not being correct

As an example:

    foo = do maybe arg1
             arg2

Would be interpreted as `foo = do { maybe arg1; arg2 }`

While

    foo = do maybe arg1
                   arg2

Would be interpreted as `foo = do { maybe arg1 arg2 }`

**Comment by treeowl** [comment]
Aside from any concerns about layout rules, it's just not what I want, and it seems I'm not alone.

**Comment by ElectricCoffee** [comment]
I posted this as an issue on StackOverflow. I got an overwhelming amount of responses saying they also had the same issue. So it seems I'm not alone either

**Comment by gracjan** [comment]
Please provide link to stack overflow question.

**Comment by ElectricCoffee** [comment]
You can find it [[here](http://stackoverflow.com/questions/32016807/haskell-indentation-doesnt-line-up-function-arguments)]

**Comment by gracjan** [comment]
Stackoverflow question has 5 comments, one of those is 'I have the same issues', other four try to be helpful.

**Comment by ElectricCoffee** [comment]
And eight upvotes.

Most people don't bother commenting on the issue, they just upvote it if they think it's a good question or if they have a similar problem

**Comment by mrkkrp** [comment]
@ElectricCoffee, currently `haskell-indentation-mode` is a bit buggy, we all should admit that. However, I had [a conversation](https://github.com/haskell/haskell-mode/issues/782#issuecomment-131324036) with author of `haskell-indentation` and he's willing to rewrite underlying parser in clearer (and thus less-buggy) manner.

I've contributed too and `haskell-indentation` will have very strong collection of tests (most of them fail for now, because tests are very intensive and `haskell-indentation-mode` is a bit buggy, as I said), so situation will improve. If you can write Emacs Lisp, consider contributing. We all use Emacs to write Haskell, but `haskell-mode` has quite a few problems and needs more men.

Look at number of issues here! At the same time there are not so many active contributors, so it will not start work smoothly by itself.

**Comment by ElectricCoffee** [comment]
I'd love to contribute, but unfortunately I don't know anywhere near enough Emacs lisp at the moment to provide any sort of useful contributions.

I'm glad it's being looked at at least. I'll try and contribute when I feel comfortable enough with my knowledge of how elisp and the emacs api is put together.

**Comment by gracjan** [comment]
Style mentioned here seems to be mostly used in data declarations, for example in `containers`:

```haskell
data IntMap a = Bin {-# UNPACK #-} !Prefix
                    {-# UNPACK #-} !Mask
                    !(IntMap a)
                    !(IntMap a)
              | Tip {-# UNPACK #-} !Key a
              | Nil
```
https://github.com/haskell/containers/blob/master/Data/IntMap/Base.hs#L277-L283

I wasn't able to find a real life example for function arguments alignment.

Note that `haskell-indentation` currently does not track the column of the *second* token in expression. This means that implementing this style requires a significant change to the algorithm.

**Comment by gracjan** [comment]
Duplicate of #82.
