### ISSUE TITLE
Scoped type annotations break indentation

### ISSUE THREAD

**Issue by arybczak** [haskell/haskell-mode#862]
The following code fragment break haskell-indentation-mode:

```haskell
foo = do
  _ :: String <- undefined
  _ :: String <- undefined
```

When you scroll to the line with the second bind and press enter, emacs displays `Illegal token: <-` and refuses to go to the next line (which in itself is a big problem, see #861).

**Comment by gracjan** [comment]
We can either:
- cover up by swallowing all exceptions and pretend that nothing happened
- make it so that every stream of letters is accepted as input and 'Illegal token' is never thrown

I would like to go the second route as it is more manageable.

The specific issue here is that type operator `::` is treated too special in indentation when it should not be so. That is architecture problem that should be solved by treating all operators same unless in contexts where it makes sense to do otherwise.
