### ISSUE TITLE
Parse error: Illegal token: where

### ISSUE THREAD

**Issue by k-bx** [haskell/haskell-mode#883]
For this code:

```haskell
main :: IO ()
main = do
    putStrLn "Hello, world"
  where
    foo = undefined
```

If I press "enter" while having a cursor at the end of a `where` word, I see an error `no catch for tag: parse-error, "Illegal token: where"`

(bug was updated with a simpler use-case)

**Comment by gracjan** [comment]
That is surprising. Would you care to add a unit test case?

**Comment by k-bx** [comment]
@gracjan sure, will try to do that (after I fill another bug-report, hehe)

**Comment by gracjan** [comment]
Sufficient test suite is a prerequisite to actually fix the indentation
problems once and for all.

**Comment by k-bx** [comment]
@gracjan can't agree more :) sorry for silly question: is there an info where tests are and how do I run them? Couldn't find on wiki.

**Comment by gracjan** [comment]
Hmm,

Tests are in 'tests' directory, specifically
'tests/haskell-indentation-tests.el'. You run them using:

make check

or

make check EMACS=/path/to/emacs

**Comment by k-bx** [comment]
Ok, added a PR with a test-case

**Comment by ivan-m** [comment]
I've just been bitten by this as well, but if I remove the `do` then it works.

**Comment by ivan-m** [comment]
I think part of it is how much the `where` is indented by: I'm using this on an existing code base in literate Haskell, where the previous programmer liked to only indent `where` by 1 space and then the contents of the where block by 1 space; if I re-indent it to be 2 spaces for both cases then it works.

(Another thing that works is to remove a bird track after the `where` so that the contents of the block are in a separate literate block, but that doesn't really solve the problem.)

**Comment by gracjan** [comment]
Interestingly, when indenting the `where` itself in code like:

```haskell
main = do
  putStrLn "Hello, world"
    where    
```

it offers two indentation positions, but when one space is added before `putStrLn` then only one indentation position is offerred:

```haskell
main = do
   putStrLn "Hello, world"
     where    
```

It seems there are more bugs around the `where` clause handling.

**Comment by gracjan** [comment]
@k-bx: thanks for the test, that really helped.

Can somebody use their eyes on the fix?
