### ISSUE TITLE
Stop blocking me from typing my code

### ISSUE THREAD

**Issue by mrkkrp** [haskell/haskell-mode#985]
Sometimes I get blocked and I cannot enter newlines. Message in minibuffer says:

> Illegal token: import

I believe it's `haskell-indentation-mode`. My opinion is that it should never block user from typing.

Not sure to reproduce this reliably, but I'll find out when I have time.

**Comment by geraldus** [comment]
Same here with
> Illegal token: where

**Comment by Shimuuar** [comment]
Also see #861 and #962

**Comment by mgsloan** [comment]
Yeah, it's pretty shocking to me that something like "intelligent" indent would have the possibility of throwing an exception and refusing to do anything.  This should just be a guess, requiring valid code before the point is absurd.

**Comment by mrkkrp** [comment]
@mgsloan, In my case I'm pretty sure code before point was valid Haskell.

**Comment by mgsloan** [comment]
Yeah, I guess my point is that "code before the point is valid Haskell" is not a reasonable requirement for automatic indentation.

**Comment by gracjan** [comment]
`haskell-indentation-mode` should work for any unicode character string, trying to make sense out of it as much as it can.

It should never throw any kind of exceptions. 

The proposed solutions seem to be to catch exceptions and cover up then. I think it should never throw in the first place. Note that there are only three places where `haskell-indentation-mode` throws:

- https://github.com/haskell/haskell-mode/blob/709903a07629eea30fefbb8087779bcbe0848a96/haskell-indentation.el#L461
- https://github.com/haskell/haskell-mode/blob/709903a07629eea30fefbb8087779bcbe0848a96/haskell-indentation.el#L769
- https://github.com/haskell/haskell-mode/blob/709903a07629eea30fefbb8087779bcbe0848a96/haskell-indentation.el#L1036

It should not be too hard to invent something sensible for each of these places to do instead of throwing exception.

Any takers?
