### ISSUE TITLE
haskell-process-do-type truncates types too aggressively

### ISSUE THREAD

**Issue by bergey** [haskell/haskell-mode#988]
When reporting a type in the message area (not inserting in the buffer), haskell-process-do-type only shows the first line and the first few chars of the second line.  `haskell-mode-message-line` has the actual truncation logic.  Because GHCi tries to format types nicely, this leads to useless output like `snugCenterV [ :: (Fracti .. ]`.  The full type is:

```
snugCenterV
  :: (Fractional (N a), HasOrigin a, Traced a, Alignable a) =>
     V a (N a) -> a -> a
```

This would fit just fine on one line on my computer (92 chars).

I'm happy to write the code to fix this, if I can get some guidance on what would be acceptable.  How about checking the minibuffer size, trying to fit on one line, and if that's not possible, truncating just enough to fit ... at the end?

**Comment by gracjan** [comment]
Make one line out of those many, turn multiple spaces into one space, get
minibuffer width and cut the line so that it does not make minibuffer
resize.

For added bonus you may also check if it looks better to also cut
everything up to "::", leaving only type. It may or may not be better,
needs to be checked.

**Comment by geraldus** [comment]
The truncation was agressive already when I worked with this stuff.  I can't be certain, but it seems that we already discussed this issue long ago, but that time we did not find good solution.  One possible alternative is to enable `Presentation Mode`.
